apiVersion: v1
kind: Service
metadata: 
  name: usermgmt-service
  labels:
    app: usermgmt-service
spec:
  type: NodePort
  selector:
    app: usermgmt
  ports:
  - port: 8095
    targetPort: 8095
    nodePort: 31231